name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mv frontend/public ./public  # Переносит содержимое public в корень
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # Путь к файлам для деплоя
      - uses: actions/deploy-pages@v4